### ISSUE TITLE
No module name msise00

### ISSUE THREAD

**Issue by taiwoojotheophilus** [space-physics/msise00#10]
Hey guys, 
I am trying to retrieve  these neutral  densities and Temperature:  [O], [N2], [O2] and Tn from this (msise00) model for a certain year, having followed the procedures of installation, I seem not to be getting the right thing, my first  question is how do I know that this has been fully installed?  
I ran this example : 
import msise00
from datetime import datetime
atmos = msise00.run(time=datetime(2013, 3, 31, 12), altkm=150., glat=65., glon=-148.)
print(atmos)
But I am receiving an error "ImportError: No module named msise00"  I am a beginner in  python..Could anyone help me please

**Comment by scivision** [comment]
Hi! I would start by moving to the top-level msis00 directory (the one you git cloned) and type
```sh
python3 -m pip install -e .
```

**Comment by scivision** [comment]
Or starting from scratch:
```sh
cd
git clone https://github.com/space-physics/msise00/
python3 -m pip install -e .
```

**Comment by taiwoojotheophilus** [comment]
I just did that, I am still receiving same error message when I used : python3 -m pip install -e .
Here  is the error message from the terminal: 
Obtaining file:///home/taiwo/msise00
Collecting geomagindices>=1.2.4 (from msise00==1.6.1)
  Using cached https://files.pythonhosted.org/packages/53/67/4709b7d8b6956b052356d07f2f5f0a4106468ccedcbb4423d02336a70db5/geomagindices-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-akga54bx/geomagindices/setup.py", line 3, in <module>
        setup()
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 110, in parse_configuration
        options.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 380, in parse
        self.section_prefix, section_name))
    distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-akga54bx/geomagindices/

**Comment by scivision** [comment]
This is a symptom of having a too-old version of setuptools, which is fixed by:

```sh
pip install --upgrade setuptools
```
