### ISSUE TITLE
Permission issue/How to change the path for data?

### ISSUE THREAD

**Issue by dcsozturk** [space-physics/msise00#11]
I run into the following error after using the msise00.run():

"PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geomagindices/data/2017'"

Is there a way to set/change the path for the data to be stored? 

The system path for the library is '/Users/username/msise00'.

Thank you.

**Comment by scivision** [comment]
This is handled automatically by Python setuptools.

As with any Python package, the `--user` option can be used when initially installing this package.  

```sh
pip install msise00 --user
```

**Comment by scivision** [comment]
what I would consider is to:

1. manually install [geomagindices](https://github.com/space-physics/geomagindices#readme) via `pip install geomagindices --user` or in development mode as per the link
2. install msise00 `pip install msise00 --user` or in development mode.

This is a general Python packaging issue, that can arise when system Python is used.
By definition, installing both packages with `pip ... --user` flag should resolve this issue.

**Comment by scivision** [comment]
I will tentatively close this issue, but if it's still bothersome, perhaps a option for data directory could be added
