### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by tdobbins** [space-physics/msise00#13]
I am having issues connecting to:

ConnectionError: Could not download the ftp file and I think the link may be broken when I tried getting to the site outside the program: ftp://ftp.swpc.noaa.gov/pub/weekly/RecentIndices.txt to /home/tdobbins/anaconda3/envs/ER/lib/python3.7/site-packages/geomagindices/data/RecentIndices.txt

**Comment by scivision** [comment]
This was fixed in MSISe00 v1.9.0. Thanks!
