### ISSUE TITLE
Question : output units ?

### ISSUE THREAD

**Issue by DavidSarria89** [space-physics/msise00#14]
Hello,

 Thanks for making this package, it is very useful to be able to run MSIS in Python.

I have a question that I did not find a clear answer.
What is the unit of the mass densities and densities given by:

```
atmos = msise00.run(input_datetime, altkm=alt/1000.0, glat=lat, glon=lon, indices=indices)
tot_mass_dens = atmos["Total"].item() # unit ?
N2_num_dens = atmos["N2"].item() # unit ?
```

I am guessing g.m-3  and m-3 by comparison with ccmc (that gives g.cm-3 and cm-3), but I want to be 100% sure.

Thanks in advance for the help.

**Comment by scivision** [comment]
* Temperature: degrees Kelvin [K]
* Density: particles per cubic meter [m^-3]
* Mass density: kilograms per cubic meter [kg m^-3]
