### ISSUE TITLE
CalledProcessError when importing the msise00 package

### ISSUE THREAD

**Issue by monesylvia** [space-physics/msise00#15]
Hi! I am new to this package and am studying this for my future work. I have an issue when importing the package. I write `import msise00` and this error pops out when the script tries to run `subprocess.py` code:

`CalledProcessError: Command '['C:\\Users\\Acer\\anaconda3\\Scripts\\ctest.EXE', '-S', 'C:\\Users\\Acer\\anaconda3\\lib\\site-packages\\msise00\\setup.cmake', '-VV']' returned non-zero exit status 4294967295.`

Anybody have the solution to this? Thank you!

**Comment by scivision** [comment]
do you get any other error messages? The problem is in the compiling step it seems

**Comment by cwesterlund94** [comment]
I am also in a very similar situation related to setting up msise00, meson, and gcc for the first time. In addition to monesylvia's error I also get:

> The Meson build system
> 
> Version: 0.54.3
> 
> Source dir: /Users/cameronwesterlund/opt/anaconda3/lib/python3.7/site-packages/msise00
> Build dir: /Users/cameronwesterlund/opt/anaconda3/lib/python3.7/site-packages/msise00/build
> Build type: native build
> Project name: msise00
> Project version: undefined
> 
> opt/anaconda3/lib/python3.7/site-packages/msise00/meson.build:1:0: ERROR: Unknown compiler(s): ['gfortran', 'flang', 'pgfortran', 'ifort', 'g95']
> The follow exceptions were encountered:
> Running "gfortran --version" gave "[Errno 2] No such file or directory: 'gfortran': 'gfortran'"
> Running "gfortran -V" gave "[Errno 2] No such file or directory: 'gfortran': 'gfortran'"
> Running "flang --version" gave "[Errno 2] No such file or directory: 'flang': 'flang'"
> Running "flang -V" gave "[Errno 2] No such file or directory: 'flang': 'flang'"
> Running "pgfortran --version" gave "[Errno 2] No such file or directory: 'pgfortran': 'pgfortran'"
> Running "pgfortran -V" gave "[Errno 2] No such file or directory: 'pgfortran': 'pgfortran'"
> Running "ifort --version" gave "[Errno 2] No such file or directory: 'ifort': 'ifort'"
> Running "ifort -V" gave "[Errno 2] No such file or directory: 'ifort': 'ifort'"
> Running "g95 --version" gave "[Errno 2] No such file or directory: 'g95': 'g95'"
> Running "g95 -V" gave "[Errno 2] No such file or directory: 'g95': 'g95'"
> 

I haven't used msise00, meson, or gcc before, so I'm unsure about where I'm going wrong. I followed the install instructions on this page's readme and am running Catalina 10.15.5.

**Comment by scivision** [comment]
Do you have a Fortran compiler installed? Does `gfortran --version` give an error?

Gfortran can be installed using [Homebrew](https://brew.sh) by

```sh
brew install gcc
```

**Comment by cwesterlund94** [comment]
I have run `brew install gcc` and `gfotran -version` gives 

> GNU Fortran (Homebrew GCC 10.1.0) 10.1.0
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by scivision** [comment]
Try the new MSISE00 v1.9.0 release, this made the setup and run more reliable. Please reopen if there's still an issue
