### ISSUE TITLE
MSISE00 error code 1

### ISSUE THREAD

**Issue by czr137** [space-physics/msise00#17]
I'm getting MSISE00 error code 1 when I run msise00 between 2011-1-1 and 2011-2-11.
This works:
```
import msise00
from datetime import datetime
atmos = msise00.run(time=datetime(2011, 2, 12, 10), altkm=150., glat=65., glon=-148.)
```
This does not (2 days earlies):
```
atmos = msise00.run(time=datetime(2011, 2, 10, 10), altkm=150., glat=65., glon=-148.)
```
## Helpful to know:

* msis pip version: 1.9.0
* operating system: Linux
* compiler & version: gfortran 5.4.0
* Python version (for Python issues): 3.7 / 3.8

**Comment by czr137** [comment]
Same with the first part of 2015.
`atmos = msise00.run(time=datetime(2015, 1, 2, 12), altkm=150., glat=65., glon=-148.)`

Error:
```
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "python3.8/site-packages/msise00/base.py", line 53, in run
    atmos = rungtd1d(time, altkm, glat.squeeze()[()], glon.squeeze()[()], indices)
  File "python3.8/site-packages/msise00/base.py", line 152, in rungtd1d
    raise RuntimeError(f"MSISE00 error code {ret.returncode}\n{ret.stderr}")
RuntimeError: MSISE00 error code 1
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
ERROR STOP 
Error termination. Backtrace:
#0  0x560bf9717398 in ???
#1  0x560bf971f1df in ???
#2  0x560bf971f3a4 in ???
#3  0x560bf9720b34 in ???
#4  0x560bf97171de in ???
#5  0x7f96dc32f151 in ???
#6  0x560bf971721d in ???
#7  0xffffffffffffffff in ???
```

**Comment by scivision** [comment]
Thank you I will look into this!

**Comment by czr137** [comment]
> Thank you I will look into this!

I can help debug today if there is anything you'd like me to update and check.

**Comment by czr137** [comment]
When I plotted some of the geomag data, there was sometimes what looked like a 1 day gap when the year rolled over. I don't know if this has anything to do with the problem.

**Comment by czr137** [comment]
Any update on this issue? I am processing a 20 year satellite dataset this week and I'd like to be able to fill in all the gaps if possible.

**Comment by scivision** [comment]
Sorry for the delay. This issue was a deeper problem that we resolved now. There are still days where the source data is missing, but now that doesn't contaminate many days of rolling averages. The time you note above now works.

fixed by msise00 v1.10.0

**Comment by czr137** [comment]
@scivision, thanks for the update, and your hard work!

**Comment by scivision** [comment]
Yes I'm sorry it took so long. With over 200 projects, and a single person, sometimes the delays are regrettable. Thanks again.
