### ISSUE TITLE
# Pytesting 5 errors

### ISSUE THREAD

**Issue by MADECICCO** [space-physics/msise00#22]
It seems it is not accepting f"..." style

====================================================== ERRORS ___________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
msise00/src/msise00/__init__.py:1: in <module>
    from .base import run, rungtd1d
E     File "/home/decicco/Documents/Programas/msise00/src/msise00/base.py", line 46
E       subprocess.check_call([cmake, f"-S{s}", f"-B{b}"] + g)
E                                            ^
E   SyntaxError: invalid syntax
___________________________________ ERROR collecting src/msise00/tests/test_grid.py ___________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
msise00/src/msise00/__init__.py:1: in <module>
    from .base import run, rungtd1d
E     File "/home/decicco/Documents/Programas/msise00/src/msise00/base.py", line 46
E       subprocess.check_call([cmake, f"-S{s}", f"-B{b}"] + g)
E                                            ^
E   SyntaxError: invalid syntax
__________________________________ ERROR collecting src/msise00/tests/test_module.py __________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
msise00/src/msise00/__init__.py:1: in <module>
    from .base import run, rungtd1d
E     File "/home/decicco/Documents/Programas/msise00/src/msise00/base.py", line 46
E       subprocess.check_call([cmake, f"-S{s}", f"-B{b}"] + g)
E                                            ^
E   SyntaxError: invalid syntax
__________________________________ ERROR collecting src/msise00/tests/test_point.py ___________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
msise00/src/msise00/__init__.py:1: in <module>
    from .base import run, rungtd1d
E     File "/home/decicco/Documents/Programas/msise00/src/msise00/base.py", line 46
E       subprocess.check_call([cmake, f"-S{s}", f"-B{b}"] + g)
E                                            ^
E   SyntaxError: invalid syntax
________________________________ ERROR collecting src/msise00/tests/test_time_grid.py _________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
msise00/src/msise00/__init__.py:1: in <module>
    from .base import run, rungtd1d
E     File "/home/decicco/Documents/Programas/msise00/src/msise00/base.py", line 46
E       subprocess.check_call([cmake, f"-S{s}", f"-B{b}"] + g)
E                                            ^
E   SyntaxError: invalid syntax

**Comment by danielk333** [comment]
F-style formatting was introduced in Python 3.6, what version were you running?
